### ISSUE TITLE
Can't install .deb package, dependency not satisfiable: libgconf2-4

### ISSUE THREAD

**Issue by lizajane999** [education/classroom-assistant#146]
I got a new computer and can't install Classroom Assistant. I'm running Kubuntu 19.04. When I try to install the .deb file, I get the error
```
This package is uninstallable
Dependency is not satisfiable: libgconf2-4
```
There is no package with that name, it is named libgconf-2-4 (with extra dash after f) on my system.

**Comment by aliutkus** [comment]
hi,
I don't understand how this issue was solved, I can't install classroom assistant due to libgconf2-4 dependency not met

**Comment by credmp** [comment]
Hi,

It seems the package was renamed at some point. My Ubuntu/Pop_OS installation lists the package as:
```
libgconf-2-4/eoan,now 3.2.6-5ubuntu3 amd64 [installed,automatic]
  GNOME configuration database system (shared libraries)
```

Regards,

Arjen

**Comment by lizajane999** [comment]
This is still an issue. I've upgraded my other computer to Kubuntu 19.10 and cannot run or reinstall classroom assistant because of unmet dependency libgconf2-4. There is a dash missing in the name, libgconf-2-4 is installed on my system.

**Comment by credmp** [comment]
From what I understand from the setup this is due to an older dependecy on electron. I tried to make sense of the npmjs registry (https://www.npmjs.com/package/electron), from what I can tell the latest version is 7.1.11.

It is the electron thing that is packaging the debian file using https://github.com/electron-userland/electron-installer-debian. That project has an open issue: https://github.com/electron-userland/electron-installer-debian/issues/141 . 

Electron seems to not be a very well maintained landscape to work in... this issue has been open for almost a year now.

**Comment by lizajane999** [comment]
Hack to force install on Ubuntu: use the `equivs` package to make a fake `libgconf2-4` package and install it, then install the classroom-assistant .deb package after. See here for instructions: http://shallowsky.com/blog/linux/install/blocking-deb-dependencies.html

**Comment by ProfBird** [comment]
I'm having the same problem on Ubuntu 19.10. When I try to install  classroom-assistant_1.0.5_amd64.deb I get this error: 
**The following packages have unmet dependencies:
 classroom-assistant : Depends: libgconf2-4 but it is not installable**

I'd like to see the package fixed rather than do a work-around. Can someone at GitHub Education tell us if there Is there a fix in the works?
