### ISSUE TITLE
Can't login to GitHub Classroom Assistant

### ISSUE THREAD

**Issue by dgomes** [education/classroom-assistant#173]
If I try to launch from the web I get a 404

From the app I get: 

![Screenshot 2020-04-24 at 00 01 10](https://user-images.githubusercontent.com/137684/80157765-d0b49f00-85be-11ea-9a92-0e5d7afa5343.png)

**Comment by dgomes** [comment]
I was able to login by opening a different assignment.

Yet I still can't get to use "Download Repositories" it always sends me a 404 :(

(I need to score those assignments pronto... hope I don't have to download 1 by 1)

**Comment by GreenDavidA** [comment]
I'm having the same issue.

**Comment by jeffrafter** [comment]
Sorry for the slow reply, we've just released a new version. Can you try in 2.0.x?

**Comment by dgomes** [comment]
Still failing... Classroom Assistant doesn't even try to open, the website gives me a 404....

**Comment by srvanderplas** [comment]
I'm also having this issue. Ubuntu 18.04 with KDE (if that matters). I've gotten it working on 2/3 of my computers, and had this issue on all of them, so it seems to occur intermittently? It would be helpful to be able to access the developer console in classroom assistant to see what the real issue is.

**Comment by jeffrafter** [comment]
(Sorry for the exceedingly long delay). I'd like to include this fix in the newest release. But I wanted to confirm this is still happening on 2.0.2. Anyone still experiencing this.

**Comment by francesquini** [comment]
I am. 
Same problem on 2.0.3.
